packages:
  - "."
  - "example"
  - "e2e"
minimumReleaseAgeExclude:
  - uuid
  - webpack
  - react
  - "react-dom"
  - "@xmldom/xmldom"
  - "@expo/dom-webview"
  - "@types/node"
  - "@algorandfoundation/wallet-provider"
  - "@algorandfoundation/react-native-keystore"
  - "@algorandfoundation/keystore"
  - "@typescript-eslint/types"
  - "@typescript-eslint/visitor-keys"
  - "react-native-nitro-modules"
  - "react-native-mmkv"
  - "expo"
  - "react-native"
  - "babel-preset-expo"
  - "@expo/config-plugins"
  - "@expo/log-box"
  - "@expo/vector-icons"
  - "expo-asset"
  - "expo-constants"
  - "expo-file-system"
  - "expo-font"
  - "expo-modules-core"
  - "jest-expo"
  - "expo-modules-autolinking"
  - "@expo/cli"
  - "@expo/config"
  - "@expo/prebuild-config"
  - "@expo/metro-config"
